### ISSUE TITLE
Batch upload multiple photos to album

### ISSUE THREAD

**Issue by tosh001** [facebook/facebook-php-sdk-v4#315] opened 2015-01-03 10:25 UTC
I am trying to use the batch upload to work with photos but I am getting an error.

For some reason it uploads the first photo but the other photos throw an error.

Is there a quick guide to get this to work?

**Comment by SammyK** [comment] 2015-01-05 22:06
What's the error? And can you provide some of the code that's throwing the error?

**Comment by tony-was** [comment] 2015-01-06 10:18
@SammyK Here is what I'm doing/what I get:

    foreach($gallery as $image) {
        $uri = [PATH-OF-LOCAL-IMAGE];
        if(File::exists($uri)) {
            $data = [
                'source' => Facebook::fileToUpload($uri),
                 'message' => 'test message',
                  'no_story' => 1
            ];
            $requests[] = Facebook::request('POST', "/$fb_album_id/photos", $data);
        }
    }

    try {
        $batchResponse = $fb->sendBatchRequest($requests, $fb->getDefaultAccessToken());
    } catch(Facebook\Exceptions\FacebookResponseException $e) {
        echo 'Graph returned an error: ' . $e->getMessage();
        exit;
    } catch(Facebook\Exceptions\FacebookSDKException $e) {
        echo 'Facebook SDK returned an error: ' . $e->getMessage();
        exit;
    }

    foreach ($batchResponse as $key => $response) {
        if ($response->isError()) {
            $error = $response->getThrownException();
            echo $key . ' error: ' . $error->getMessage() . "<br>";
        } else {
            $response = $response->getGraphObject();
        }
    }

Now for some reason the first image uploads without any dramas but the second image gets this error:

    object(Facebook\FacebookResponse)[380]
        protected 'httpStatusCode' => int 500
        ...
        'value' => string 'OAuth "Facebook Platform" "invalid_request" "Invalid parameter"' (length=63)
        protected 'body' => string '{"error":{"message":"Invalid parameter","type":"FacebookApiException","code":100,"error_subcode":1366046,"is_transient":false,"error_user_title":"Can't Read Files","error_user_msg":"Your photos couldn't be uploaded. Photos should be less than 4 MB and saved as JPG, PNG, GIF or TIFF files."}}' (length=292)
        protected 'decodedBody' => 
            array (size=1)
                'error' => 
                    array (size=7)
                        'message' => string 'Invalid parameter' (length=17)
                        'type' => string 'FacebookApiException' (length=20)
                        'code' => int 100
                        'error_subcode' => int 1366046
                        'is_transient' => boolean false
                        'error_user_title' => string 'Can't Read Files' (length=16)
                        'error_user_msg' => string 'Your photos couldn't be uploaded. Photos should be less than 4 MB and saved as JPG, PNG, GIF or TIFF files.' (length=107)

From what I have looked at it has something to do with the function Facebook::fileToUpload($uri) as it seems not to be setting the correct data for any image after the first one.

I understand that this version is still in dev but any feedback would be appreciated!

Thanks

**Comment by tony-was** [comment] 2015-01-06 12:02
btw tosh001 is my other account

**Comment by SammyK** [comment] 2015-01-06 22:16
What are the files you're trying to upload? The error indicates that the file is of the wrong type or is too big.

**Comment by SammyK** [comment] 2015-01-09 16:54
Those are the best examples of batch file uploads for sure.

Are you uploading the same file for everything? I'm curious if Facebook is banning a batch of the same file as a spam filter or something.

Also - `fileToUpload()` and `request()` should not be called statically as you are in the code you posted. You should use the `$fb` instance like so:

```php
$data = [
    'source' => $fb->fileToUpload($uri),
    'message' => 'test message',
    'no_story' => 1
];
$requests[] = $fb->request('POST', "/$fb_album_id/photos", $data);
```

**Comment by SammyK** [comment] 2015-01-09 16:58
PS: On this line:

```php
$batchResponse = $fb->sendBatchRequest($requests, $fb->getDefaultAccessToken());
```

You don't have to specify `$fb->getDefaultAccessToken()` as the SDK will automatically fallback to the default access token. You can can remove it:

```php
$batchResponse = $fb->sendBatchRequest($requests);
```

**Comment by SammyK** [comment] 2015-01-29 00:09
@gfosco This can close

@tony-was If you're still having trouble let us know!

**Comment by tony-was** [comment] 2015-02-01 09:43
@SammyK sorry I haven't had a chance to look at your response until now.

Your wizardry has done it. the images are uploading without any dramas! thanks for that!

**Comment by tony-was** [comment] 2015-02-01 10:32
I do have one more question regarding access tokens. If I have an access token as a string how do I extend this token?

is it something like $fb->extend($tokenstring);

or do I have to use a workaround?

**Comment by SammyK** [comment] 2015-02-02 20:40
@tony-was Glad it worked! :)

To extend an access token from a string on the master branch right now you need to create an access token entity first:

```php
$app = $fb->getApp();
$client = $fb->getClient();

$token = new Facebook\AccessToken('token-as-string');
$longToken = $token->extend($app, $client);
```

But once #330 gets merged in, the API will change and you will need to do it like this:

```php
$oAuth2Client = $fb->getOAuth2Client();

$longToken = $oAuth2Client->getLongLivedAccessToken('{access-token}');
```

Hope that helps! :)

**Closed** 2015-02-02 21:05 UTC

**Comment by tony-was** [comment] 2015-02-04 11:20
works perfectly (used the second method using #330)

thanks again for all your hard work!

**Comment by SammyK** [comment] 2015-02-04 15:58
No problem! Glad you got it working! :)

**Comment by nirmalthumber** [comment] 2016-12-23 08:07
hello sir,

I am also trying to use the batch upload to work with photos to timeline not in album.
For some reason it uploads the first photo but the other photos throw an error.

Is there a quick guide to get this to work?
Here is the error
`[headers:protected] => Array
        (
            [Content-Type] => text/javascript; charset=UTF-8
            [Facebook-API-Version] => v2.8
            [WWW-Authenticate] => OAuth "Facebook Platform" "invalid_request" "Invalid parameter"
            [Expires] => Sat, 01 Jan 2000 00:00:00 GMT
            [Cache-Control] => no-store
            [Vary] => Accept-Encoding
            [Pragma] => no-cache
            [Access-Control-Allow-Origin] => *
        )

    [body:protected] => {"error":{"message":"Invalid parameter","type":"OAuthException","code":100,"error_subcode"
:1366046,"is_transient":false,"error_user_title":"Can't Read Files","error_user_msg":"Your photos couldn't
 be uploaded. Photos should be less than 4 MB and saved as JPG, PNG, GIF or TIFF files.","fbtrace_id"
:"Efvn5K1H8q8"}}
    [decodedBody:protected] => Array
        (
            [error] => Array
                (
                    [message] => Invalid parameter
                    [type] => OAuthException
                    [code] => 100
                    [error_subcode] => 1366046
                    [is_transient] => 
                    [error_user_title] => Can't Read Files
                    [error_user_msg] => Your photos couldn't be uploaded. Photos should be less than
 4 MB and saved as JPG, PNG, GIF or TIFF files.
                    [fbtrace_id] => Efvn5K1H8q8
                )

        )`

**Comment by yguedidi** [comment] 2016-12-23 19:39
@nirmalthumber The error message is explicit: Your photos couldn't be uploaded. Photos should be less than 4 MB and saved as JPG, PNG, GIF or TIFF files.

**Comment by junaidatique** [comment] 2017-07-04 21:50
@yguedidi the files are less than 4 mb and valid jpg files but still these are not uploaded. I had similar issue with twitter which I fixed using [this](https://stackoverflow.com/a/28701786). Please suggest something like this.

**Comment by yguedidi** [comment] 2017-07-04 22:39
@junaidatique Thank you for your feedback! Please tell me which PHP version you use? With which HTTP client: cURL, Guzzle or streams?

**Comment by junaidatique** [comment] 2017-07-05 18:31
@yguedidi I am using php version 5.6 and my fb sdk version is 4.0

**Comment by yguedidi** [comment] 2017-07-05 20:30
@junaidatique the HTTP client you use is also import, which it is?
PS: considere upgrading the SDK version to at 5.5 :)

**Comment by yguedidi** [comment] 2017-07-05 20:33
@junaidatique BTW, based on this [Guzzle config documentation](http://docs.guzzlephp.org/en/stable/request-options.html#verify) and [this change in PHP5.6](http://php.net/manual/en/migration56.openssl.php#migration56.openssl.peer-verification), I think your OpenSSL configuration is broken

**Comment by junaidatique** [comment] 2017-07-07 17:41
@yguedidi  I am googling for two days now but I am unable for OpenSSL configuration. Can you recommend me changes? Thanks in advance.

**Comment by yguedidi** [comment] 2017-10-29 10:30
@junaidatique is it working now?

**Comment by junaidatique** [comment] 2017-11-01 14:24
yes. I did some changes in the library I think so. The issue is resolved. thanks for your help.

**Comment by yguedidi** [comment] 2018-02-25 14:55
@junaidatique maybe you could contribute your changes? :)
